{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-yardstick
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/yardstick_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/yardstick/yardstick_{{ version }}.tar.gz
  sha256: ebf113ad1d6554dd5d17181148a8c9e51166d4fa579e9540756d01ef61b71d2b

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - r-hardhat                  # [build_platform != target_platform]
    - r-dplyr                    # [build_platform != target_platform]
    - r-tidyselect               # [build_platform != target_platform]
    - r-generics                 # [build_platform != target_platform]
    - r-vctrs                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr >=1.0.9
    - r-generics >=0.1.2
    - r-hardhat >=1.0.0
    - r-rlang >=1.0.2
    - r-tidyselect >=1.1.2
    - r-vctrs >=0.4.1
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-dplyr >=1.0.9
    - r-generics >=0.1.2
    - r-hardhat >=1.0.0
    - r-rlang >=1.0.2
    - r-tidyselect >=1.1.2
    - r-vctrs >=0.4.1

test:
  commands:
    - $R -e "library('yardstick')"           # [not win]
    - "\"%R%\" -e \"library('yardstick')\""  # [win]

about:
  home: https://github.com/tidymodels/yardstick
  license: MIT
  summary: Tidy tools for quantifying how well model fits to a data set such as confusion matrices, class probability curve summaries, and regression metrics (e.g., RMSE).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: yardstick
# Type: Package
# Title: Tidy Characterizations of Model Performance
# Version: 0.0.4
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", c("aut")), person("Davis", "Vaughan", , "davis@rstudio.com", c("aut", "cre")), person("RStudio", role = "cph"))
# Description: Tidy tools for quantifying how well model fits to a data set such as confusion matrices, class probability curve summaries, and regression metrics (e.g., RMSE).
# URL: https://github.com/tidymodels/yardstick
# BugReports: https://github.com/tidymodels/yardstick/issues
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# Depends: R (>= 2.10)
# Suggests: testthat, covr, purrr, tidyr, ggplot2, knitr, kableExtra, rmarkdown
# Imports: dplyr, utils, pROC (>= 1.15.0), rlang (>= 0.4.0), tidyselect, Rcpp, generics
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2019-08-26 18:59:32 UTC; davis
# Author: Max Kuhn [aut], Davis Vaughan [aut, cre], RStudio [cph]
# Maintainer: Davis Vaughan <davis@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-08-26 22:40:02 UTC
