{% set version = '0.0.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-yardstick
  version: {{ version|replace("-", "_") }}

source:
  fn: yardstick_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/yardstick_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/yardstick/yardstick_{{ version }}.tar.gz
  sha256: 0374f683f388df7fd13146e64691189aefe35aaf2baff5565f6a8f197dccf836

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-dplyr
    - r-proc
    - r-rlang
    - r-tidyselect
    - r-rcpp
    - r-generics
  run:
    - r-base
    - r-dplyr
    - r-proc
    - r-rlang
    - r-tidyselect
    - r-rcpp
    - r-generics

test:
  commands:
    - $R -e "library('yardstick')"           # [not win]
    - "\"%R%\" -e \"library('yardstick')\""  # [win]

about:
  home: https://github.com/topepo/yardstick
  license: GPL-2
  summary: 'Tidy tools for quantifying how well model fits to a data set such as confusion matrices,
    class probability curve summaries, and regression metrics (e.g., RMSE). '
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
