{% set version = '0.0.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-yardstick
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/yardstick_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/yardstick/yardstick_{{ version }}.tar.gz
  sha256: 0374f683f388df7fd13146e64691189aefe35aaf2baff5565f6a8f197dccf836

build:
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-dplyr
    - r-generics
    - r-proc
    - r-rlang
    - r-tidyselect
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-dplyr
    - r-generics
    - r-proc
    - r-rlang
    - r-tidyselect

test:
  commands:
    - $R -e "library('yardstick')"           # [not win]
    - "\"%R%\" -e \"library('yardstick')\""  # [win]

about:
  home: https://github.com/tidymodels/yardstick
  license: GPL-2
  summary: 'Tidy tools for quantifying how well model fits to a data set such as confusion matrices,
    class probability curve summaries, and regression metrics (e.g., RMSE). '
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast

# Package: yardstick
# Type: Package
# Title: Tidy Characterizations of Model Performance
# Version: 0.0.2
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", c("aut", "cre")), person("Davis", "Vaughan", , "davis@rstudio.com", c("aut")), person("RStudio", role = "cph"))
# Maintainer: Max Kuhn <max@rstudio.com>
# Description: Tidy tools for quantifying how well model fits to a data set such as confusion matrices, class probability curve summaries, and regression metrics (e.g., RMSE).
# URL: https://github.com/tidymodels/yardstick
# BugReports: https://github.com/tidymodels/yardstick/issues
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.0.9000
# Depends: R (>= 2.10)
# Suggests: testthat, covr, purrr, tidyr, ggplot2, knitr, kableExtra, rmarkdown
# Imports: dplyr, utils, pROC, rlang, tidyselect, Rcpp, generics
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2018-11-05 20:32:41 UTC; davis
# Author: Max Kuhn [aut, cre], Davis Vaughan [aut], RStudio [cph]
# Repository: CRAN
# Date/Publication: 2018-11-05 21:00:03 UTC
