{% set version = "0.0.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-yardstick
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/yardstick_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/yardstick/yardstick_{{ version }}.tar.gz
  sha256: d8895fa6040fe431b2188a4b61c6470a4850551fdb970f844bd6f7472ca43bfb

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-dplyr
    - r-generics
    - r-proc >=1.15.0
    - r-rlang >=0.4.0
    - r-tidyselect
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-dplyr
    - r-generics
    - r-proc >=1.15.0
    - r-rlang >=0.4.0
    - r-tidyselect

test:
  commands:
    - $R -e "library('yardstick')"           # [not win]
    - "\"%R%\" -e \"library('yardstick')\""  # [win]

about:
  home: https://github.com/tidymodels/yardstick
  license: GPL-2.0-only
  summary: Tidy tools for quantifying how well model fits to a data set such as confusion matrices, class probability curve summaries, and regression metrics (e.g., RMSE).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: yardstick
# Type: Package
# Title: Tidy Characterizations of Model Performance
# Version: 0.0.4
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", c("aut")), person("Davis", "Vaughan", , "davis@rstudio.com", c("aut", "cre")), person("RStudio", role = "cph"))
# Description: Tidy tools for quantifying how well model fits to a data set such as confusion matrices, class probability curve summaries, and regression metrics (e.g., RMSE).
# URL: https://github.com/tidymodels/yardstick
# BugReports: https://github.com/tidymodels/yardstick/issues
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# Depends: R (>= 2.10)
# Suggests: testthat, covr, purrr, tidyr, ggplot2, knitr, kableExtra, rmarkdown
# Imports: dplyr, utils, pROC (>= 1.15.0), rlang (>= 0.4.0), tidyselect, Rcpp, generics
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2019-08-26 18:59:32 UTC; davis
# Author: Max Kuhn [aut], Davis Vaughan [aut, cre], RStudio [cph]
# Maintainer: Davis Vaughan <davis@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-08-26 22:40:02 UTC
